language: node_js
sudo: false
services:
- docker
node_js:
- 7
script:
- yarn build
- mkdir public/public_html/
- mv dist public/public_html/dist
- mv index.html public/public_html/
- tar c public | ssh dokku@ung.utt.fr tar:in gamejam.utt.fr
before_install:
- openssl aes-256-cbc -K $encrypted_b20da4393c19_key -iv $encrypted_b20da4393c19_iv -in id_rsa.enc -out id_rsa -d
- apt-get update -y &>/dev/null
- which ssh-keyscan || (apt-get install -y ssh &>/dev/null)
- which git || (apt-get install -y git &>/dev/null)
- which gzip || (apt-get install -y gzip &>/dev/null)
- which ssh-agent || (apt-get install openssh-client -y)
- mkdir -p ~/.ssh
- eval $(ssh-agent -s)
- ssh-add <(echo .travis/id_rsa)
- echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
- ssh-keyscan -H ung.utt.fr >> ~/.ssh/known_hosts